apiVersion: v1
kind: Service
metadata:
  name: erkan3
  namespace: cnv-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    kubevirt.io/domain: erkan3
    vm.kubevirt.io/name: erkan3
  sessionAffinity: None
  type: ClusterIP



